// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopBoss.Web.Data;

#nullable disable

namespace ShopBoss.Web.Migrations
{
    [DbContext(typeof(ShopBossDbContext))]
    [Migration("20250711000000_StatusStandardization")]
    partial class StatusStandardization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            // This migration adds Status fields to Product and DetachedProduct entities
            // The complete model will be updated in the ModelSnapshot
#pragma warning restore 612, 618
        }
    }
}